### ISSUE TITLE
Pricing?

### ISSUE THREAD

**Issue by azohra** [Erudika/scoold-pro#1]
Hi, 
We are looking at pro but there is no listed price anywhere. 

blog post: https://erudika.com/blog/2018/10/15/Announcing-Scoold-Pro/
buy page: https://paraio.com/scoold-pro 
main website: https://scoold.com/

We are not comfortable entering our credit card information without understanding the purchase price.

**Comment by albogdano** [comment]
Scoold Pro is 299 EUR. I've made it more clear.
![image](https://user-images.githubusercontent.com/346873/47901717-64555580-de89-11e8-97f8-6dd564335ce7.png)
