### ISSUE TITLE
Request: Let not admin users have an E-Mail notification on new questions

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold-pro#10]
With versin 1.33.0 only admin users can enable notification E-Mails for new questions. Since this is a very helpful tool to motivate users to participate, please add this notification also to non-admin users.

**Comment by albogdano** [comment]
Should this be replaced by the summary email feature #11? I think it may get a bit spammy if there are lots of new questions each day.

**Comment by b-morgenthaler** [comment]
I see #11 optional for every user (not just for admins). This request (#10) is a must have feature to be configured by admins for everybody working with Scoold at our company.

 

But I see you point that #11 might not be neccessary anymore if #10 is available.

 

For us, #11 has higher prio than #10.

 

Von: Alex Bogdanovski <notifications@github.com> 
Gesendet: Montag, 2. September 2019 15:18
An: Erudika/scoold-pro <scoold-pro@noreply.github.com>
Cc: Morgenthaler Björn <Bjoern.Morgenthaler@comlet.de>; Author <author@noreply.github.com>
Betreff: Re: [Erudika/scoold-pro] Request: Let not admin users have an E-Mail notification on new questions (#10)

 

Should this be replaced by the summary email feature #11 <https://github.com/Erudika/scoold-pro/issues/11> ? I think it may get a bit spammy if there are lots of new questions each day.

**Comment by b-morgenthaler** [comment]
Sorry, I mixed up the issue numbers:

 

#10 is optional and might not be neccessary anymore because #11 is available and a must have for us.

 

Still, #11 has higher prio, though :)

 

Von: Morgenthaler Björn 
Gesendet: Montag, 2. September 2019 15:49
An: reply@reply.github.com; scoold-pro@noreply.github.com
Cc: author@noreply.github.com
Betreff: AW: [Erudika/scoold-pro] Request: Let not admin users have an E-Mail notification on new questions (#10)

 

I see #11 optional for every user (not just for admins). This request (#10) is a must have feature to be configured by admins for everybody working with Scoold at our company.

 

But I see you point that #11 might not be neccessary anymore if #10 is available.

 

For us, #11 has higher prio than #10.

 

Von: Alex Bogdanovski <notifications@github.com <mailto:notifications@github.com> > 
Gesendet: Montag, 2. September 2019 15:18
An: Erudika/scoold-pro <scoold-pro@noreply.github.com <mailto:scoold-pro@noreply.github.com> >
Cc: Morgenthaler Björn <Bjoern.Morgenthaler@comlet.de <mailto:Bjoern.Morgenthaler@comlet.de> >; Author <author@noreply.github.com <mailto:author@noreply.github.com> >
Betreff: Re: [Erudika/scoold-pro] Request: Let not admin users have an E-Mail notification on new questions (#10)

 

Should this be replaced by the summary email feature #11 <https://github.com/Erudika/scoold-pro/issues/11> ? I think it may get a bit spammy if there are lots of new questions each day.

**Comment by albogdano** [comment]
This features is now available to all users.
