### ISSUE TITLE
Request: Add summary E-Mail

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold-pro#11]
To increase motivation for users to participate (e. g. in a corporate context), we believe a summary E-Mail of all new questions is a key features.

Please add a settings detail for admins to configure an E-Mail summary report with configurable duration (daily, every other day, weekly) and dedicated receiving E-Mail (e.g. a public distribution list). If enabled this report shall be mandatory for all users.

This report shall contain at least the following content:

- List off all new questions since last report
- Every list entry shall show at least the subject to let the reader decide if it's interessting and she/he may help to answer
- Every list entry shall be linked to its URL so the reader can direcly jump into it

**Comment by albogdano** [comment]
[Done](https://github.com/Erudika/scoold#periodic-summary-emails).
