### ISSUE TITLE
Request: Quote users with "@"

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold-pro#13]
Tools like Jira or Google Docs let you quote users with "@username".

Please add this also to Scoold for questions, comments and answers. 

If "@" is typed a list of all users will show up to help find the correct username. If found, "@username" will show up as hyperlink to the user's profile and the quoted user will get a notification E-Mail (maybe configurable).

**Comment by albogdano** [comment]
I'll see what I can do about this. Something similar is available in the Slack integration.

**Comment by albogdano** [comment]
[Done](https://github.com/Erudika/scoold#mentions)
