### ISSUE TITLE
self hosted docker makes requests to outside urls

### ISSUE THREAD

**Issue by merlin-tc** [Erudika/scoold-pro#14]
We are testing scoold as an internal system.

Docker was a quick and easy way to install it but we noticed that several outside URLs are called.
We do have a strict network policy so on some systems we won't allow connection to:

- cloudflare.com
- googleapis.com
- unpkg.com

Is there a way to disable fetching of external resources?

**Comment by albogdano** [comment]
Unfortunately you can't turn this off. I was thinking about making the site use only local assets but didn't find the time to make the switch.

**Comment by albogdano** [comment]
This has been fixed except for MathJax which still loads from CDNJS. MathJax is not enabled by default so you shouldn't have any problems.
