### ISSUE TITLE
German translation for "Report a problem" is misleading

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold-pro#16]
We use following  version of Scoold Pro:

- Scoold Pro
- Scoold version: 1.35.1
- Production mode: true
- Para app: app:scoold
- Para version: 1.34.1
- Para endpoint: http://localhost:8080

The German translation for "Report a problem" is misleading, since "Bericht" means more of a statistic analysis report. If you want to report a problem in German, "Melden" would be a better fit.

**Comment by albogdano** [comment]
what is the plural form of "melden"? Is it "meldet"?

**Comment by b-morgenthaler** [comment]
The present tense verb „melden“ (to report) conjugates to

 

*	I „melde“
*	you „meldest“
*	he/she/it „meldet“
*	we „melden“
*	you „meldet“
*	they „melden“

 

http://konjugator.reverso.net/konjugation-deutsch-verb-melden.html

 

If you tell me the the English sentence, maybe I can give you a better tranlation hint.

 

Von: Alex Bogdanovski <notifications@github.com> 
Gesendet: Mittwoch, 2. Oktober 2019 12:08
An: Erudika/scoold-pro <scoold-pro@noreply.github.com>
Cc: Morgenthaler Björn <Bjoern.Morgenthaler@comlet.de>; Author <author@noreply.github.com>
Betreff: Re: [Erudika/scoold-pro] German translation for "Report a problem" is misleading (#16)

 

what is the plural form of "melden"? Is it "meldet"?

**Comment by albogdano** [comment]
There are 5 occurrences of the word "Bericht" in `lang_de.properties` and one of them is "Berichte" for `reports.title = Berichte`. That's a plural noun for "Reports". So replacing "Bericht" will result in these changes:
```
reports.title = Meldet
report = Melden
reports.category = Meldenskategorie
about.badges.reporter = für jeden eingereichten Melden
about.reports.1 = ...Jeder Melden, den du sendest, hilft dabei, dass Scoold ein netter und freundlicher Ort bleibt.
```

**Comment by b-morgenthaler** [comment]
Ok, I think my request was a bit confusing, sorry about that.

 

I was talking about the verb „melden“ as a better translation for „Bericht“. My impression was that „Bericht“ as a noun in order to translate „report“ should be more a verb describing an action item like „close“ or „pin to top“.

 

In German, it’s perfectly fine to translate „report a problem“ with  „Ein Problem melden“.

 

If you stick to this translation pattern („melden“ and „Problem“ instead of „Bericht“) here’s my suggestions for all translations:

 

reports.title = Meldungen //(noun plural)
 
report = melden //(verb infinitive)
 
reports.category = Meldekategorie //(noun)
 
about.badges.reporter = für jede eingereichte Meldung //(noun singular)
 
about.reports.1 = ...Jedes Problem, das du meldest, hilft dabei, dass Scoold ein netter und freundlicher Ort bleibt.
 
I hope this is clearing things up a bit :)

 

 

Von: Alex Bogdanovski <notifications@github.com> 
Gesendet: Mittwoch, 2. Oktober 2019 12:25
An: Erudika/scoold-pro <scoold-pro@noreply.github.com>
Cc: Morgenthaler Björn <Bjoern.Morgenthaler@comlet.de>; Author <author@noreply.github.com>
Betreff: Re: [Erudika/scoold-pro] German translation for "Report a problem" is misleading (#16)

 

There are 5 occurrences of the word "Bericht" in lang_de.properties and one of them is "Berichte" for reports.title = Berichte. That's a plural noun for "Reports". So replacing "Bericht" will result in these changes:

reports.title = Meldet
 
report = Melden
 
reports.category = Meldenskategorie
 
about.badges.reporter = für jeden eingereichten Melden
 
about.reports.1 = ...Jeder Melden, den du sendest, hilft dabei, dass Scoold ein netter und freundlicher Ort bleibt.

**Comment by albogdano** [comment]
Thanks for the help @b-morgenthaler!
