### ISSUE TITLE
Filtering of certain tags is not working correctly

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold-pro#17]
We use following  version of Scoold Pro:

- Scoold Pro
- Scoold version: 1.35.1
- Production mode: true
- Para app: app:scoold
- Para version: 1.34.1
- Para endpoint: http://localhost:8080

We use a custom space where we put all users in by default: "comlet".

We heavily rely on tags for filtering questions. For exactly one tag we encountered that it is not filtered correctly for our custom space mentioned above.
The tag is called "scooled-pro" (I know it's a typo ;-)). If you click on this tag for filtering, within "comlet" space the list of questions is empty for all users.
If you try this with an admin account that is able to switch from "comlet" space to "default space", the filtering in "default space" is working as expected, i. e. the list of questions is not empty.
All questions have been asked within "comlet" space.

**Comment by albogdano** [comment]
By filtering you mean "Questions tagged with scoold-pro" and not "filter by favorite tags"?
You are right about the first one - If I go to `/questions/tag/scooled-pro` I should be able to see questions with this tag but there're no results. That's a confirmed bug.

**Comment by b-morgenthaler** [comment]
Yes, in this case it's "Questions tagged with scooled-pro"
