### ISSUE TITLE
Request to have local avatar images

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold-pro#19]
We use following  version of Scoold Pro:

- Scoold Pro
- Scoold version: 1.35.1
- Production mode: true
- Para app: app:scoold
- Para version: 1.34.1
- Para endpoint: http://localhost:8080

With the ability to have images saved locally, would it be possible to have also locally saved images for avatars?

Maybe even with just drag&drop an image to the user's avatar configuration like one is able to do within qestions?

**Comment by albogdano** [comment]
Done.

**Comment by b-morgenthaler** [comment]
With version

Scoold Pro
Scoold version: 1.36.0
Production mode: true
Para app: app:scoold
Para version: 1.34.2

Drag'n Drop for local avatar images is working well. 
But unfortunately I could not delete it anymore. I could change it to gravatar but not into default state, i. e. no avatar.

**Comment by albogdano** [comment]
Ok, I've added a "clear" which will switch to the default avatar.
![image](https://user-images.githubusercontent.com/346873/74053912-9424ce80-49e5-11ea-9d9f-daa849d325d2.png)

**Comment by b-morgenthaler** [comment]
Thank you.

Von meinem iPhone gesendet
