### ISSUE TITLE
Show list of possible users when referencing with @ earlier

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold-pro#20]
We use following  version of Scoold Pro:

- Scoold Pro
- Scoold version: 1.35.1
- Production mode: true
- Para app: app:scoold
- Para version: 1.34.1
- Para endpoint: http://localhost:8080

When referencing users with "@" then it seems that the list of possible users to select from pops up after the first part of a user's name has been written completely.

Is is possible to show the list of possible users to chose from earlier, i. e. after the first three characters have been typed?

For example, the user "John Smith" is referenced. His name is showing up in the list only after either "John" or "Smith" has been typed completely. If one cannot tell the exact spelling of a user's name, it would be helpful this list shows up already after either "Joh" or "Smi" has been typed.
This would make the list of possible users longer but more helpful in my opinion.

**Comment by albogdano** [comment]
Done.
