### ISSUE TITLE
Microsoft Teams integration

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold-pro#23]
Hi,

since you already implemented a Slack integration: Is it also possible to have a Teams integration as well?

**Comment by albogdano** [comment]
You'll have to be a bit more specific. How would Scoold be integrated with MS Teams?

**Comment by b-morgenthaler** [comment]
Sorry, since I don’t know how your Slack integration works (and I am not a Slack expert), I didn’t want to give you any constraints.

 

Here are a few scenarios I can think of:

*	New questions are posted to MS Team’s newsfeed

*	Alternative: a dedicated team (and maybe channel) where all new questions are posted

*	Interacting with Scoold directly by chatting, e. g. asking a new question and getting the replies directly to the Teams chat

 

What are the possibilities with the Slack integration?

 

Von: Alex Bogdanovski <notifications@github.com> 
Gesendet: Freitag, 7. Februar 2020 15:58
An: Erudika/scoold-pro <scoold-pro@noreply.github.com>
Cc: Morgenthaler Björn <Bjoern.Morgenthaler@comlet.de>; Author <author@noreply.github.com>
Betreff: Re: [Erudika/scoold-pro] Feature-Request: Microsoft Teams integration (#23)

 

You'll have to be a bit more specific. How would Scoold be integrated with MS Teams?

**Comment by albogdano** [comment]
So my initial understanding was that Teams was a more than a business chat application. But now I see that it's very similar to Slack and Mattermost. I think we could have the same integration for Teams as for Slack. The integration points are:
- ability to mention teammates + notifications
- ability to get notified when a new question is posted on Scoold
- ability to ask or answer a Scoold question directly from chat
- ability to approve/reject new questions directly from chat

I can see this integration happening but I really cannot say when. Such integrations take a significant amount of time and I probably won't be able to start working on it in the next couple of months. I will update this thread when this feature is in progress.

**Comment by b-morgenthaler** [comment]
Thank you. Looking forward to it.
One thing for you to consider: other third-party tools interact with Teams as an "App". Maybe this is also something you can look into.

**Comment by albogdano** [comment]
> The most important MS Teams integration is basic embedding, which I believe it would work correctly with an MS Teams website tab. Further, it would be nice to have:
> 
>  - notifications in teams
>  - mention notifications
>  - question saving/following for notifications
> 
> I guess all of the above are somehow a subset of Scoold - MS Teams notification integration.
> 
> A distinct nice feature would be an option so that whenever someone tries to write something on a specific channel, an automatic search would start on scoold questions, and a pop up would show with links towards those questions. Similarly to what happens when you try to write a question on stackoverflow, but for channels as well. This would prevent a lot of “please check this question (scoold link)”.

**Comment by Zarkstar** [comment]
Hello, is there any news regarding an integration with MS Teams? The organization I work for will probably switch from Slack to Teams and we're currently evaluating if we should buy a license for Scoold or not

**Comment by albogdano** [comment]
@Zarkstar I am currently working on this. Estimated release window is 1-2 months. If it gets done sooner I will notify you here.

**Comment by albogdano** [comment]
The Scoold-Teams integration is ready! 🎉 
Read more about it in [this blog post](https://erudika.com/blog/2021/07/23/Scoold-Pro-now-integrates-with-Microsoft-Teams/)
