### ISSUE TITLE
Unable to login to scoold app

### ISSUE THREAD

**Issue by jpascor-intellective** [Erudika/scoold-pro#25]
I've setup scoold app on AWS Ubuntu, running own para instance, yet I'm unable to login with the following error - "Authentication failed or was canceled"

**Comment by albogdano** [comment]
I don't have enough information to answer your question. Please, check all
the logs and follow the readme.

**Comment by jpascor-intellective** [comment]
here's the error I get when I attempt to login:
Invalid signature for request GET /v1/_id/mylogin coming from app scoold

**Comment by albogdano** [comment]
Check your Para access keys because they are probably invalid. More details about that error can be found in Erudika/scoold#141
