### ISSUE TITLE
How to incorporate resources in jar version of Scoold-pro?

### ISSUE THREAD

**Issue by jjorba** [Erudika/scoold-pro#28]
Hi

In the Scoold readme you mention some possibilities of IU customisation, e.g. logo:

para.logo_url = "/logo.svg"
para.logo_width = 90

but where "/logo.svg" need to be, in scoold-pro jar version? In jar working directory doesn't work.

What is needed to be done? ... jar extraction, including resources, and jar packaging again ?

It is related with that the "uploads" directory that appears during execution? or which is the function of that directory?

Thanks

**Comment by albogdano** [comment]
`para.logo_url` takes either a relative URI like `/path/to/logo.svg` or an absolute URL to an image. I would recommend that you use an absolute URL like `https://public_fileserver/logo.svg`. You can technically extract the JAR and repackage it but that's not recommended. The location of the logo image has nothing to do with the `uploads` directory. So don't put it there or anywhere around the JAR file, unless you have a file server like nginx to serve static resources (*.svg, *.png, etc). If you have this kind of setup where the path `/path/to/logo.svg` is served by the local file server, then using a relative URI will work just fine.

**Comment by jjorba** [comment]
Thanks, I have precissely a nginx installed, i will do in this manner.
