### ISSUE TITLE
CSP violation: cannot login with MS Edge

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold-pro#33]
Hi,

since version 1.37.1 of Scoold Pro, it's not possible to log in with MS Edge (44.17763.831.0) because of a CSP violation. Previous versions worked fined. CSP violation E-Mails get send (26x) with following content. If you need the real URLs/hostnames, just let me know. I will forward the original E-Mail to you privately.

In the log file there's no output regarding this issue (didn't enable debug log, though).

![Anmerkung 2020-03-27 115619](https://user-images.githubusercontent.com/52192619/77749466-5e35bb00-7022-11ea-8fb4-2c803287401f.png)

![Anmerkung 2020-03-27 120000](https://user-images.githubusercontent.com/52192619/77749684-b8cf1700-7022-11ea-80a2-16abd654302a.png)

**Comment by albogdano** [comment]
I am aware of that. Unfortunately Scoold won't support Edge prior to version 80. The old Edge is now considered obsolete. The workaround here is to disable the CSP completely with `para.csp_header_enabled = false`.

**Comment by b-morgenthaler** [comment]
Ok. I think I missed the part where older Edge versions are not supported. Do you have a link where the supported browsers are listed?

**Comment by albogdano** [comment]
Yes, here's the list of supported browsers implementing CSP3:
 https://caniuse.com/#feat=mdn-http_headers_csp_content-security-policy_strict-dynamic

**Comment by albogdano** [comment]
Fixed by changing the CSP header slightly.
