### ISSUE TITLE
Feature request: save session after timeout

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold-pro#36]
Hi,
we are using

>Scoold Pro
Scoold version: 1.39.2
Production mode: true
Para app: app:scoold
Para version: 1.37.0

For security reasons, our session times out fairly quickly:

> session_timeout: 1800

When the session times out during asking/editing (without saving) all changes made are gone after time out. Would it be possible to save the session state, so that after re-login the last edit is still available?

**Comment by albogdano** [comment]
This could be a potential bug as this feature is already implemented with JavaScript. I'll check.
