### ISSUE TITLE
E-Mail notification settings are not saved

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold-pro#4]
Having installed this version:

Scoold Pro
Scoold version: 1.32.0
Production mode: false
Para app: app:scoold
Para version: 1.31.2
Para endpoint: http://localhost:8080

Steps to reproduce:
- Change account's E-Mail notification settings
- Click Save button
- Restart Scoold server application (e. g. due to a config change or update)
- Navigate to account's E-Mail notification settings; they do not represent the previously saved state anymore

**Comment by albogdano** [comment]
Thanks for reporting this issue Björn! I'm hoping to fix it today. Expect a new release soon.

**Comment by albogdano** [comment]
This should be fixed in `1.32.1` (released today). I will reopen it if necessary.
