### ISSUE TITLE
Preview button (Ctrl+P) should render LaTeX equations using MathJax

### ISSUE THREAD

**Issue by couviphi** [Erudika/scoold-pro#41]
When entering a LaTeX equation like $E =  \gamma m c^2$, the preview button (Ctrl+P) should use MathJax and render the LaTeX equation using MathJax exactly the same as it will appear once the question is saved, that is the same as in the image shown below:
![image](https://user-images.githubusercontent.com/13632654/89253542-c64c6d00-d5d1-11ea-8294-2927ff23bf2f.png)

**Comment by albogdano** [comment]
Fixed! Thanks for reporting!

**Comment by couviphi** [comment]
Thank you for your quick reply. That was really fast!

As of tonight (Aug 4, 10pm Pacific Time), I am not seeing the fix yet in action on the live Pro Demo site https://pro.scoold.com/

The image below shows what I am seeing during Preview when replying to a question:
![image](https://user-images.githubusercontent.com/13632654/89373373-5acfd180-d69d-11ea-8240-9472e9fa548e.png)

My expectation is the following:
![image](https://user-images.githubusercontent.com/13632654/89373615-05e08b00-d69e-11ea-8bc4-e02cc44d3566.png)

I still see the same problem when asking a new question: the Preview button does not render LaTeX as MathJax.

**Comment by albogdano** [comment]
I've updated the demo site with the latest fixes.

**Comment by couviphi** [comment]
I have tested the Preview button works fine for both Question and Answer. LaTeX is now properly formatted during Preview. This enhancement/fix makes it much easier to enter LaTeX equations without having to leave the Scoold user-interface to check if the LaTeX equations are correct/valid. 
Thank you very much for your quick turnaround!
Case closed.
