### ISSUE TITLE
User cannot mention any other users

### ISSUE THREAD

**Issue by jorgeag68** [Erudika/scoold-pro#44]
A specific user cannot mention anyone on Scoold.

Using @ doesn't display any user names.

He can be mentioned by other users.

To try to fix the issue I've deleted the user and he logged in again from LDAP.

The problem still persists and now all his questions are assigned to "Deleted user"

How can we fix these 2 issues ?

**Comment by albogdano** [comment]
Is that user a member of any spaces? Does that user see any other people on the Users page? 
To fix the "deleted user" issue you have to manually edit the `profile`  and `user` objects in Para of the user in question and set their `id` property to be equal to the previous `id` value of that user.

**Comment by jorgeag68** [comment]
Hello,

We don't use spaces Just the Default space.. And no, the users in question can't see any other users... 
More than one now with this problem.


I've tried to edit the User and Profile to set the id to the old one.
I'm using console.paraio.org  and can see all the data. But when I save changes nothing is changed on the data.

**Comment by albogdano** [comment]
This issue can be related to a bug which was introduced in a previous release. I will release the patched version now.
Changing the `id` of an object is not possible with an "update" operation. Instead you can copy the JSON data from one object and create a new object, paste the data and edit the `id`. Do this for both `profile` and `user` objects of that user. Finally, after you verify that all works well, delete the old objects. The `id` of a `profile` object is in the format `123456:profile`

**Comment by jorgeag68** [comment]
Hi,

Thanks. Waiting for the patched version.

Meanwhile I could create the new profile with the old id but can't create the user. I get this error:

{
  "code" : 400,
  "message" : "Failed to authenticate user with 'password'. Check if user is active."
}

What can be done ?

**Comment by jorgeag68** [comment]
Hello,

Looks like the issue is back on the new release 1.40.2. All non admin users have this problem.

scoold-pro-1.40.2.jar

Can you please check the problem and issue a new version to fix this ?

regards,
<img width="1150" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/23095798/96692222-b301a000-137d-11eb-8e48-8ff7ec7dfb32.png">

**Comment by albogdano** [comment]
Alas, you're right @jorgeag68! This will be fixed in the next release but in the new version you will have to add all users to the default space like this:
![image](https://user-images.githubusercontent.com/346873/96772704-33f78080-13ec-11eb-8b64-679bd4367e5c.png)
Go to Users > Bulk Edit > Add "Default space" to "All users"

**Comment by jorgeag68** [comment]
Thank you for confirming. 

I'll be waiting to get the new software.

**Comment by jorgeag68** [comment]
Any news about dates for the release of the new build?

**Comment by albogdano** [comment]
@jorgeag68 Yes, I am preparing a new release for tomorrow.
