### ISSUE TITLE
Issues in Docker deployment

### ISSUE THREAD

**Issue by blemke1971** [Erudika/scoold-pro#47]
I am using Scoold Pro and attempting to setup a server in our internal network.   I am using docker to spin up the para and scoold images.   I have the access and secret key set in the config however my scoold application never finds the para backend.   It simply continues to post the message "No connection to Para backend. Retrying connection in".  Is there any configuration options to enable to set that can get me some sort of more detailed error about why its not finding the backend?

**Comment by aryankhandal0** [comment]
https://github.com/Erudika/scoold/issues/180#issuecomment-652485461
You have to set para.endpoint in scoold-application.conf. Docker Networking is what you've to understand, from what I gathered from your problem.

**Comment by albogdano** [comment]
@blemke1971 check you docker container networking and specifically the exact IP address of your Para container.

**Comment by albogdano** [comment]
https://github.com/Erudika/scoold#docker

**Comment by blemke1971** [comment]
I had have hardcoded the para container and scoold container to a static IP within the docker-compose.   I can verify that the para endpoint is operational as I have written a .NET client to connect to it to pull some basic data.   But the scoold front end just refuses to connect with no good error messages.  Is there no flags or additional logging that I can turn on to try to figure out why it cannot connect?

**Comment by albogdano** [comment]
Ok, can you share your docker-compose file or do you use the default one? There's no need to check the logs as the issue is obvious - the Scoold container cannot communicate with the Para container or the app key and secret are incorrect for your Scoold app. You have created a separate app for Scoold rather than using `app:para`, correct?

**Comment by blemke1971** [comment]
Here is the compose file

`version: '3.2'

services:
   para:
     image: erudikaltd/para
     networks:
       app_net:
         ipv4_address: 172.16.238.10
     ports:
       - "8080:8080"
     volumes:
       - type: volume
         source: paraData
         target: /para/data
       - type: volume
         source: paraLib
         target: /para/lib
       - type: bind
         source: ./para-application.conf
         target: /para/application.conf
     restart: always
     env_file: para.env

   scoold:
     depends_on:
       - para
     image: 374874639893.dkr.ecr.eu-west-1.amazonaws.com/scoold-pro:1.40.3
     networks:
       app_net:
         ipv4_address: 172.16.238.15
     ports:
       - "8000:8000"
     volumes:
       - type: bind
         source: ./scoold-application.conf
         target: /scoold/application.conf
     restart: always
     env_file: scoold.env

volumes:
  paraData:
  paraLib:

networks:
  app_net:
    ipam:
      driver: default
      config: 
        - subnet: "172.16.238.0/24"
`

**Comment by albogdano** [comment]
Ok, I'm assuming you have `para.endpoint = "http://172.16.238.10:8080"` in your `./scoold-application.conf` file? Have you tried setting `para.endpoint = "http://para:8080"`?

**Comment by blemke1971** [comment]
Yeah I tried the IP direct and that didnt seem to like things.   I have not tried the para address yet.

**Comment by aryankhandal0** [comment]
I was able to run with scoold image, I dont know if there is a problem with scoold-pro but I am sharing all my files. [GistLink](https://gist.github.com/aryankhandal0/2f56d0c916d7f136860a83dc1948d825). 
[INFO ] Connected to Para backend.
Please note that you have to create app through para-cli change the secret key in scoold-application.conf and then run again, this is no reason for no connection to backend (AFAIK).

**Comment by albogdano** [comment]
@blemke1971 Just use `para.endpoint = "http://para:8080"` in `scoold-application.conf`.
![image](https://user-images.githubusercontent.com/346873/101048586-69ff5700-358b-11eb-8c49-763dcab066ea.png)
I'm using the same docker-compose YAML file with this configuration for Scoold Pro:
```ini
para.env = "development"
para.app_name = "Scoold"
para.endpoint = "http://para:8080"
para.access_key = "app:scoold"
para.secret_key = "secret...."
```

**Comment by blemke1971** [comment]
I tore down the environment and cleared out my local mount points and reconfigured everything from the ground up with a static network in docker and it seems to be working now.   Thanks for your time
