### ISSUE TITLE
External URL blocked

### ISSUE THREAD

**Issue by hhentati** [Erudika/scoold-pro#48]
When users click on URL on the comment section, it redirects to "about:blank#blocked", is there any option to allow this action?
thanks for your help.

**Comment by albogdano** [comment]
Never seen this before. This must be browser-specific. Which browser do you use?

**Comment by hhentati** [comment]
Thank you for your reply,
Tested on chrome : it redirects to "about:blank#blocked"
Firefox : when click on the link nothing happens.

Best regards

**Comment by albogdano** [comment]
I can't reproduce this behavior on my side. You could have a browser addon blocking the links. Try this URL at the bottom there's a link in a comment which I can open https://live.scoold.com/question/1176796443415941120/is-it-possible-for-moderators-or-admins-to-approve-answers-of-any-question

**Comment by albogdano** [comment]
Closed - no response, no reproducible steps given.
