### ISSUE TITLE
Auto assign spaces to new users does not work

### ISSUE THREAD

**Issue by a-durst** [Erudika/scoold-pro#5]
Having installed this version:

Scoold Pro
Scoold version: 1.32.0
Production mode: false
Para app: app:scoold
Para version: 1.31.2
Para endpoint: http://localhost:8080

Environment:
* default space is public
* "new" default space to be: comlet

we try to add all new users to comlet

so added to configuration:
para.auto_assign_spaces = "comlet"

also tried:
scooldspace:comlet
and scooldspace:comlet:comlet

but none worked

**Comment by albogdano** [comment]
Hi @a-durst, I'm sorry but you'll have to wait a bit more until the next Pro release, i.e. this feature is not released yet. I was too quick to update the README. New release coming really soon.

**Comment by albogdano** [comment]
Closing this because `1.32.1` is released today. I will reopen it if necessary.
