### ISSUE TITLE
Feature request: Add ability to create custom badge

### ISSUE THREAD

**Issue by AKN-Edo** [Erudika/scoold-pro#53]
I think that creating custom badges may have several positive aspects, even if they could only be assigned manually by an admin/moderator. Is that an implementable feature?

**Comment by albogdano** [comment]
Yes, it would be a nice feature to have. 
We are talking about simple labels on the user profile right? Typically, badges in Scoold have associated logic which determines the amount of reputation which will be gained when the badge is obtained.
Custom badges would be implemented in the form of very simple labels.

**Comment by AKN-Edo** [comment]
Yes, labels (I was thinking about images, like medals? But text would also be fine, if implementing images is too complicated) is what I was thinking about. The primary use would be, in my opinion, to boost the gamification of the tool, providing unique and custom prizes for particular users.

**Comment by albogdano** [comment]
Implemented in Scoold `1.50.0`.
