### ISSUE TITLE
no users are shown under /people 

### ISSUE THREAD

**Issue by dittertp** [Erudika/scoold-pro#65]
Hi,

in version 1.57.3 the user listing seems to be broken (list is always empty). The API endpoint /api/users also only returns an empty array. I only use the default space. In version 1.57.2 everything works fine.

**Comment by albogdano** [comment]
Yes, correct - this is a bug which is fixed in `master` and I will soon release `1.57.4`. Erudika/scoold@48b7153683095c100ac9e6654dca58b9eb4a05af
